config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  post 'main/locate'
  post 'main/set_shop'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :shop
  belongs_to :product

  validates :shop, uniqueness: { scope: :product }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :prices, dependent: :destroy
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :prices

  def self.get_closest_shop lat, long
    @shops = Array.new

    Shop.all.each { |shop| @shops << { shop_id: shop.id, distance: distance_to_shop([lat, long], [shop.lat, shop.long]) } }

    @shops.min_by { |shop| shop[:distance] }[:shop_id]
  end

  private
  def self.distance_to_shop loc1, loc2
    loc1[0] = loc1[0].to_f
    loc1[1] = loc1[1].to_f
    loc2[0] = loc2[0].to_f
    loc2[1] = loc2[1].to_f
    rad_per_deg = Math::PI/180
    rkm = 6371
    rm = rkm * 1000

    dlat_rad = (loc2[0]-loc1[0]) * rad_per_deg
    dlon_rad = (loc2[1]-loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    (rm * c).round
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @shop = session[:current_shop] ? Shop.find(session[:current_shop]) : Shop.last
  end

  def locate
    if params[:location][:lat].nil? || params[:location][:long].nil? || params[:location][:reset] != 'true' && session[:shop_allocated] == 'manual'
      render :status => :bad_request
      return
    end

    session.delete(:shop_allocated)

    @closest_shop = Shop.get_closest_shop params[:location][:lat], params[:location][:long]

    if session[:current_shop].to_i != @closest_shop
      session[:current_shop] = @closest_shop
      render partial: 'show_closest.js.erb'
    end
  end

  def set_shop
    session[:current_shop] = params[:shop_picker][:shop]
    session[:shop_allocated] = 'manual'
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= form_with scope: :location, url: main_locate_path, id: 'location-form', class: 'd-none' do |form| %>
      <%= form.hidden_field :reset %>
      <%= form.hidden_field :lat %>
      <%= form.hidden_field :long %>
    <% end %>

    <div class="container py-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/_show_closest.js.erb
if(confirm('Мы нашли ближайший к вам магазин, показать его?'))
  Turbolinks.visit(window.location)

app/views/main/index.html.erb
<div id="show-closest-button" class="btn btn-primary">Показать ближайший</div>
<%= form_with scope: :shop_picker, url: main_set_shop_path, class: 'mt-3' do |form| %>
  <div class="form-group">
    <%= form.label 'Магазины' %>
    <%= form.select :shop, options_from_collection_for_select(Shop.all, 'id', 
      'address', 
      session[:current_shop] ? session[:current_shop] : Shop.first.id.to_s), {}, 
      class: 'ml-3 custom-select w-50' %>
    <%= form.submit 'Показать', class: 'ml-3 btn btn-primary' %>
  </div>
<% end %>

<div class="row">
  <% @shop.prices.each do |price| %>
    <div class="col-sm-12 mt-3">
      <div class="card product-card">
        <div class="card-body">
          <h5 class="card-title"><%= price.product.name %></h5>
          <h6 class="card-subtitle mt-2 text-muted"><%= price.price %> Руб.</h6>
        </div>
      </div>
    </div>
  <% end %>
</div>